namespace :test do
  desc "Seeds database"
  task bayes_classifier: :environment do
    b = BayesSuicideClassifier.new
    Sentimental.load_defaults
    b.train_on_training_posts
    s = Sentimental.new(0)


    #


    j1 = "Forgot to do this before I started coding today. Actually had a dream last night (really more of a nightmare) that I couldn't authorize OAuth and failed the project. Clearly having some sort of anxiety about this whole thing. Today has gone in waves - I am using a really thorough testing/organizational approach to this project which is making me a) feel really solid on the parts I have implemented so far but b) freak out about how I'm not as far as everyone else. Which is kind of silly because everyone is doing something different so I really can't compare...but I still feel behind as fuck. Focusing on writing waffle cards and knocking functionality out bit by bit. Also need to figure out what API im actually consuming. Hah."

    j2 = "Went for a ride with Brant today. It occurred to me then, that I have been anxious and upset about the possibility I would never have someone like Sarah in my life, and how much I missed her. I shared this. I've felt sad all afternoon, but I am content."

    j3 = "Rough day. Anxiety over everything, but I had a great bike ride in the sun and therapist session. I may or may not feel confident about the future and moving forward into the last two weeks of this module."

    j4 = "As with every project I feel like I have no idea where to start or how to organize what I'm trying to do and . I've started with wireframes and mapping out some initial user stories to help get a feel for what I want to see/do as a user. That being said, I'm anxious about each individual piece for different reasons. I think it will be important for me take small bites and build on it slowly. First bite will be O Auth with facebook and a landing page."

    j5 = "The last 72 hours has been a pretty weird one for me. It started out on Friday by having an extremely emotional day where I showed up tired only to find I was to be one of the subjects of a Gear Up session which I had no idea about until that morning. However, I ended out following my own advice and confronting the person who was responsible for that and felt a whole lot better afterwards since we worked through it. The rest of the day also turned into a kind of emotional roller coaster with some pretty real conversations between me and my friends that extended well into Saturday. I ended out having a long conversation with Dan on Sunday about the fact that his brother and his girlfriend were breaking up and what it means to compromise in a relationship. It leaves me in kind of an odd place this Monday because while I'm happy with most of the discussions that I had over the weekend, some of them still feel pretty open ended. I'm also nervous about my personal project because I'm going to be pulling in a lot of data from a lot of different places and I'm still not sure how to handle all of that. I'm hoping Josh or some other instructor will be willing to sit down with me to work through some of this issues early in the week."

    j6 = "Working on and thinking about the personal project most of the day. Happy with how it's going so far, but feel some unknown problems looming on the horizon. Also, why should I implement OAuth when the last thing I want is to add gate to this app that does not need one? I tried to duck out early before protocol, but then saw it's now 'required', so I turned it on around. I feel a bit anxious about the looming job hunt, but also excited. Just like everyone else probably feels. So, NOT INTERESTING, I'M SORRY AARON. Does caps lock register as angry? Hard to know, so I'll just go make some spaghetti and meatballs. Spaghetti and meatballs should register as happy."

    j7 = "This morning I participated in a guided meditation with Adam, Turing alum. It was an interesting experience... I spent much of the time upset, with my mind furiously smashing against itself as I refused to understand why I was unable to relax. I imagined it as a hollow glass egg filled with thrashing lava. Imagining it break and release allowed me some respite. Afterwards, though, I felt amazing! - unlike I have after a meditation."

    j8 = "Today was a better day. I got more done on my project than I thought, which felt good. I have some very awesome supportive friends at school, which makes this easier. I am still apprehensive about the project, I am not in uncharted territory yet, where I will have to teach myself how to do things no other student has done yet. It was also a little discouraging that I did not follow the lecture very well this morning. I don't have a grasp on javascript yet and it feels like Turing is not going to teach us it as well as they have ruby. I'm annoyed we haven't learned to test it yet, even though they require us to use it on a project now. Hopefully we'll all teach each other things and get through this together. I am so grateful for the people I have at Turing, I could not do this without them."

    j9 = "I am feeling super overwhelmed right now! Personal project, assessment looming, lightning talk this week, caucus tonight.. finding time to eat/sleep/rest.. Just trying to take one day at a time, to take small manageable steps.. I want to pass this module so, so badly."

    j10 = "Personal project is going decently well, farther along in a shorter amount of time than I had anticipated. That should allow for more complex analysis / extra extensions so I feel confident I'll do well on the assessment. Feeling somewhat nervous about the final assessment due to a new/different format, but should be fine after this week practicing with an external API and possibly creating an internal API."

    j11 = "Shit. I always forget to write this! Keep reminding us. So I have been far less productive today than I was yesterday, but oddly enough I feel OK about that. Wine at lunch with my friend Allison might have helped/been the culprit of that. BUT I also had a checkin with Lovisa that got me really excited about this project. I was kind of freaking out about my API situation (or lack thereof), but what excites me about the project is implementing the other cool stuff like Redis and recording videos, and starting a chat session between users. I'll get to the API eventually but she made me feel better about not making that a point of anxiety at this point. Getting into styling a little bit to make it production ready with what I've got so far...but still have SO much to do. As long as I don't overthink that part I feel great!"

    j12 = "I am stuck in a hellish environment problem. It's frustrating because I wish we had more training about how our environment works. I now feel behind in my project, and my instructor believed I could have gotten this project done in 20 hours. That's the problem when people think you are smart, you have to deliver and I will be disappointed in myself if I don't. I am now feeling tired and burnt out, which is terrible considering I have a ton of shit to do on this project still (it's only day 2). I'm hoping to power through tomorrow, but we'll see. I feel like crying every 10 minutes, but I don't want people to think I'm the stereotypical girl who cries when things get hard, especially at a school with 70% guys. Hoping for progress and faith in myself."

    j13 = "I feel so bad right now. Like, such a failure at this, unable to figure out the simplest things, for certain I will not pass this module.. I'm closer to wanting to quit than I ever have been before. I'm tired. I'm sad. I'm frustrated. If I felt like I had any other option, if someone presented me with some other option for not continuing to be destitute, I think I would take it."

    j14 = "I kind of feel like a dork writing about myself like this as if I were an American pop-rock icon-demi God, or a self-confessed product of corporate-packaged rebellion, but I’ve heard so many insanely exhaggerated stories or reports from my friends and Ive read so many pathetic second rate, freudian evaluations from interviews from my childhood up until the present state of my personality and how I’m a notoriously f—ed up heroine addict, alcoholic, self destructive, yet overtly sensitive, frail, fragile, soft spoken, narcoleptic, neurotic, little pissant who at any minute is going to O.D. jump off a roof wig out blow my head off or all 3 at once. Oh Pleez GAWD I can’t handle the success! The success! And I feel so incredibly guilty! For abandoning my true commrades who were the ones who are devoted who were into us a few years ago. And in 10 years when NIRVANA becomes as memorable as Kajagoogoo that same very small percent will come to see us at reunion gigs sponsored by Depends diapers, bald fat still trying to RAWK at amusement parks. Saturdays: puppet show, rollercoaster & Nirvana . . ."

    j15 = "The last 72 hours has been a pretty weird one for me. It started out on Friday by having an extremely emotional day where I showed up tired only to find I was to be one of the subjects of a Gear Up session which I had no idea about until that morning. However, I ended out following my own advice and confronting the person who was responsible for that and felt a whole lot better afterwards since we worked through it. The rest of the day also turned into a kind of emotional roller coaster with some pretty real conversations between me and my friends that extended well into Saturday. I ended out having a long conversation with Dan on Sunday about the fact that his brother and his girlfriend were breaking up and what it means to compromise in a relationship. It leaves me in kind of an odd place this Monday because while I'm happy with most of the discussions that I had over the weekend, some of them still feel pretty open ended. I'm also nervous about my personal project because I'm going to be pulling in a lot of data from a lot of different places and I'm still not sure how to handle all of that. I'm hoping Josh or some other instructor will be willing to sit down with me to work through some of this issues early in the week."

    j16 = "Working on and thinking about the personal project most of the day. Happy with how it's going so far, but feel some unknown problems looming on the horizon. Also, why should I implement OAuth when the last thing I want is to add gate to this app that does not need one? I tried to duck out early before protocol, but then saw it's now 'required', so I turned it on around. I feel a bit anxious about the looming job hunt, but also excited. Just like everyone else probably feels. So, NOT INTERESTING, I'M SORRY AARON. Does caps lock register as angry? Hard to know, so I'll just go make some spaghetti and meatballs. Spaghetti and meatballs should register as happy."

    j17 = "Today was a better day. I got more done on my project than I thought, which felt good. I have some very awesome supportive friends at school, which makes this easier. I am still apprehensive about the project, I am not in uncharted territory yet, where I will have to teach myself how to do things no other student has done yet. It was also a little discouraging that I did not follow the lecture very well this morning. I don't have a grasp on javascript yet and it feels like Turing is not going to teach us it as well as they have ruby. I'm annoyed we haven't learned to test it yet, even though they require us to use it on a project now. Hopefully we'll all teach each other things and get through this together. I am so grateful for the people I have at Turing, I could not do this without them."

    j18 = "I am stuck in a hellish environment problem. It's frustrating because I wish we had more training about how our environment works. I now feel behind in my project, and my instructor believed I could have gotten this project done in 20 hours. That's the problem when people think you are smart, you have to deliver and I will be disappointed in myself if I don't. I am now feeling tired and burnt out, which is terrible considering I have a ton of shit to do on this project still (it's only day 2). I'm hoping to power through tomorrow, but we'll see. I feel like crying every 10 minutes, but I don't want people to think I'm the stereotypical girl who cries when things get hard, especially at a school with 70% guys. Hoping for progress and faith in myself."

    j19 = "I feel so bad right now. Like, such a failure at this, unable to figure out the simplest things, for certain I will not pass this module.. I'm closer to wanting to quit than I ever have been before. I'm tired. I'm sad. I'm frustrated. If I felt like I had any other option, if someone presented me with some other option for not continuing to be destitute, I think I would take it."

    j20 = "My life is going to be a farm where I’ll grow my food. I won’t do nothing but sit under a tree while my crops are growing, drink homemade wine, write novels to edify my soul, play with my kids, and thumb my nose at the coughing wretches."

    j21 = "Today I felt more or less completely out of control.  I became incredibly frustrated with the project, lots of things are mostly but not completely working, and it is a huge pain.  I was angry.  I was short with people.  And mostly I was not at all in the moment.  I tried to calm down a couple of times, but... mild success at best.  Felt wildly unfocused earlier in the day too, at union station specifically."

    j22 = "It seems as if I have been spending all my life apologizing to you for things that happened whether they were my fault or not.  I am enclosing your pin because I want you to think of what you took from me every time you see it.  I don't want you to think I would kill myself over you because you are not worth any emotion at all.  It is what you cost me that hurts and nothing can replace it."

    22.times do |i|
      puts "j#{i+1}, #{b.classifier.classify(eval("j#{i+1}"))}"
      puts "j#{i+1}, #{s.get_sentiment(eval("j#{i+1}"))}"
      puts "j#{i+1}, #{s.get_score(eval("j#{i+1}"))}"
    end
  end
end
