# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cb69b7d8ba6ab22a91d3ce017aaed9470dbe984f42f8a6034438793382f8a567bc2151f5b09f9cc9093f2c091de775dfc4e9a6a71f57475fdb4059e5bd69923

test:
  secret_key_base: 68ab095af15cef7d3a861f44b635746e3ad8f22652b1ffe34a106bcd6ecc01e09b5aa42f4d3b13f7aca94a92686401ba2895574d4b355e71ca2e915a3cc645f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  new_relic_license: <%= ENV["NEW_RELIC_LICENSE"]
